services:
  postgres:
    image: postgres:latest
    container_name: customer_management_db
    restart: always
    environment:
      POSTGRES_DB: customer_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: