spring:
  application.name: customer-management
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_management
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html